spring:
  activemq:
    broker-url: ${MB_URL:tcp://localhost:61616}
    user: ${MB_ADMIN_LOGIN:admin}
    password: ${MB_ADMIN_PASSWORD:admin}

jms:
  queue:
    in: ${MB_IN_QUEUE:to.remote}
    out: ${MB_OUT_QUEUE:to.front}

logging:
  charset:
    console: "UTF-8"
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p){highlight} %clr([%15.15t]){faint} %clr(%-40.40logger{0}){magenta} %clr(:){faint} %clr(%m%n){highlight}"
  level:
    org.springframework: INFO