version: "3.7"
services:
  front:
    image: 'companiesinfo/front-controller:latest'
    build:
      context: front
    container_name: front-controller
    ports:
      - "8080:8080"
    environment:
      - DB_ADDRESS=http://db:8081
    depends_on:
      - db
  db:
    image: 'companiesinfo/repository:latest'
    build:
      context: persistence/repository
    container_name: repository
    ports:
      - "8081:8081"