server:
  port: 8080
  servlet:
    context-path: /info
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
  error:
    whitelabel.enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: on_param

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none
    properties.hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:info
    username: sa
    password:
  sql:
    init:
      mode: always
  #    data-locations: classpath:schema.sql, classpath:data.sql
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  charset:
    console: "UTF-8"
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n"
  level:
    org.springframework: INFO

