DROP TABLE articles IF EXISTS;
DROP TABLE products IF EXISTS;
DROP SEQUENCE GLOBAL_SEQ IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE products
(
    id                      INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name                    VARCHAR(150)    NOT NULL,
    description             VARCHAR(200)    NOT NULL,
    implementation_cost     INTEGER         NOT NULL
);
CREATE UNIQUE INDEX products_unique_idx
    ON products (name);

CREATE TABLE articles
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    product_id      INTEGER                         NOT NULL,
    name            VARCHAR(150)                    NOT NULL,
    content         VARCHAR(5000)                   NOT NULL,
    date            DATE            DEFAULT now()   NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX articles_unique_idx
    ON articles (product_id, name);

