# - Информация о продукте

### Создать информацию о продукте
POST http://localhost:8081/products
Content-Type: application/json;charset=UTF-8

{
  "name":"Новый продукт",
  "description":"Описание Нового продукта",
  "implementationCost":300000
}

### Получить информацию о продукте
GET http://localhost:8081/products/100001

### Получить информацию по всем продуктам
GET http://localhost:8081/products

### Фильтр по имени
GET http://localhost:8081/products?filterBy=name&filter=дин

### Фильтр по цене
GET http://localhost:8081/products?filterBy=implementationCost&costFrom=200100

### Сортировка по цене
GET http://localhost:8081/products?sortBy=implementationCost

### Обновить информацию о продукте
PUT http://localhost:8081/products/100001
Content-Type: application/json

{
  "id":100001,
  "name":"Обновленный продукт",
  "description":"Описание обновленного продукта",
  "implementationCost":450000
}

### Удалить информацию о продукте
DELETE http://localhost:8081/products/100001

# - Статьи о продукте

### Создать статью
POST http://localhost:8081/articles
Content-Type: application/json;charset=UTF-8

{
  "name":"Статья про НОВЫЙ продукт",
  "productId":100000,
  "content":"Содержание статьи о НОВОМ продукте",
  "date":"2012-04-23T18:25:43.511Z"
}

### Получить статью
GET http://localhost:8081/articles/100005

### Получить все статьи
GET http://localhost:8081/articles

### Фильтр по имени
GET http://localhost:8081/articles?filterBy=name&filter=пер

### Фильтр по дате
GET http://localhost:8081/articles?filterBy=date&toDate=2022-09-20

### Сортировка по id восходящая
GET http://localhost:8081/articles?sortBy=id

### Обновить статью
PUT http://localhost:8081/articles/100004
Content-Type: application/json

{
  "id": 100004,
  "name": "Обновленная статья про второй продукт",
  "productId": 100000,
  "content": "Обновленное содержание статьи-2 о втором продукте"
}

### Удалить статью
DELETE http://localhost:8081/articles/search/del?id=100005

# - Актуатор

###
GET http://localhost:8081/monitor